sha1: use standard uint32_t integer type
Use the C99 standard uint32_t type instead of the implementation
specific u_int32_t.

This fixes the following compile error when building with musl libc:

  In file included from sha1.c:28:0:
  sha1.h:11:5: error: unknown type name 'u_int32_t'
       u_int32_t state[5];
       ^