Fix tls-groups test to match handshake error wording across OpenSSL platforms (#15689)
### Issue 

Failed daily CI :
>*** [err]: TLS: Verify tls-groups with disjoint groups in
tests/unit/tls.tcl
Expected 'Could not connect to Redis at 127.0.0.1:27121: SSL_connect
failed: ssl/tls alert handshake failure
child process exited abnormally' to match '*sslv3 alert handshake
failure*' (context: type eval line 10 cmd {assert_match {*sslv3 alert
handshake failure*} $e} proc ::test)
Cleanup: may take some time... OK
Error: Process completed with exit code 1.

CentOS reports `ssl/tls alert handshake failure`, so the test failed.